# Generated by vendorctl. build-system: plain-make. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           bzip2
Version:        1.0.8
Release:        1%{?dist}
Summary:        Block-sorting file compressor (static-musl, oxide)
License:        bzip2-1.0.6
URL:            https://sourceware.org/bzip2/
Source0:        bzip2-1.0.8.tar.gz

%description
Block-sorting file compressor (static-musl, oxide)

%prep
%setup -q -n bzip2-1.0.8

%build
SYS=/home/nd/oxide/rpmbuild/sysroot/%{name}/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-oxide-gcc; CXX=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-oxide-g++; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin; TRIPLE=aarch64-buildroot-linux-musl; else CC=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-oxide-gcc; CXX=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-oxide-g++; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin; TRIPLE=x86_64-buildroot-linux-musl; fi
UAPI=""
export PATH="$SYS/usr/bin:$TCBIN:$PATH"
export CC_FOR_BUILD=gcc BUILD_CC=gcc CXX
export CC UAPI
OXIDE_CFLAGS=""; export OXIDE_CFLAGS
for s in blocksort huffman crctable randtable compress decompress bzlib; do "$CC" -c -Os -D_FILE_OFFSET_BITS=64 "$s.c"; done
"$CC" -static -Os -D_FILE_OFFSET_BITS=64 -o bzip2 blocksort.o huffman.o crctable.o randtable.o compress.o decompress.o bzlib.o bzip2.c

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/bin
install -m0755 bzip2 %{buildroot}/usr/bin/bzip2
mkdir -p %{buildroot}/usr/bin
ln -s bzip2 %{buildroot}/usr/bin/bunzip2
mkdir -p %{buildroot}/usr/bin
ln -s bzip2 %{buildroot}/usr/bin/bzcat
( cd %{buildroot} && find . -type f -o -type l ) | sed 's#^\.##' | LC_ALL=C sort > %{_builddir}/bzip2.files

%files -f %{_builddir}/bzip2.files
%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 1.0.8-1
- Generated oxide spec (plain-make family).
