# Generated by vendorctl. build-system: plain-make. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           bzip2
Version:        1.0.8
Release:        1%{?dist}
Summary:        Block-sorting file compressor (static-musl, oxide)
License:        bzip2-1.0.6
URL:            https://sourceware.org/bzip2/
Source0:        %{name}-%{version}.tar.gz

%description
Block-sorting file compressor (static-musl, oxide)

%prep
%setup -q

%build
. /home/nd/oxide/rpmbuild/lib/uapi-stage.sh
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc; UAPI="$(uapi_cflags aarch64)"; else CC=musl-gcc; UAPI="$(uapi_cflags x86_64)"; fi
export CC UAPI
for s in blocksort huffman crctable randtable compress decompress bzlib; do "$CC" -c -Os -D_FILE_OFFSET_BITS=64 "$s.c"; done
"$CC" -static -Os -D_FILE_OFFSET_BITS=64 -o bzip2 blocksort.o huffman.o crctable.o randtable.o compress.o decompress.o bzlib.o bzip2.c

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/bin
install -m0755 bzip2 %{buildroot}/usr/bin/bzip2
mkdir -p %{buildroot}/usr/bin
ln -s bzip2 %{buildroot}/usr/bin/bunzip2
mkdir -p %{buildroot}/usr/bin
ln -s bzip2 %{buildroot}/usr/bin/bzcat

%files
/usr/bin/bzip2
/usr/bin/bunzip2
/usr/bin/bzcat

%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 1.0.8-1
- Generated oxide spec (plain-make family).
