# Generated by vendorctl. build-system: cargo. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           choose
Version:        1.3.6
Release:        1%{?dist}
Summary:        choose: human cut/awk alternative (oxide)
License:        MIT OR Apache-2.0
Source0:        %{name}-%{version}.tar.gz

%description
choose: human cut/awk alternative (oxide)

%prep
%setup -q -n choose-1.3.6

%build
unset CC CXX CPP CFLAGS CXXFLAGS CPPFLAGS LDFLAGS
if [ "%{_target_cpu}" = "aarch64" ]; then TGT=aarch64-unknown-linux-musl; export PATH="/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin:$PATH"; export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc; export CC_aarch64_unknown_linux_musl=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc; else TGT=x86_64-unknown-linux-musl; fi
rustup target add $TGT >/dev/null 2>&1 || true
RUSTFLAGS="-C target-feature=+crt-static" cargo build --release --target $TGT 

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/bin
install -m0755 target/%{_target_cpu}-unknown-linux-musl/release/choose %{buildroot}/usr/bin/choose

%files
/usr/bin/choose

%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 1.3.6-1
- Generated oxide spec (cargo family).
