# Generated by vendorctl. build-system: script. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           cmake
Version:        3.31.6
Release:        1%{?dist}
Summary:        CMake build system (oxide)
License:        BSD-3-Clause
Source0:        cmake-3.31.6.tar.gz

%description
CMake build system (oxide)

%prep
%setup -q -n cmake-3.31.6

%build
SYS=/home/nd/oxide/rpmbuild/sysroot/%{name}/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-oxide-gcc; CXX=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-oxide-g++; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin; TRIPLE=aarch64-buildroot-linux-musl; TCSYS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/aarch64-buildroot-linux-musl/sysroot; else CC=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-oxide-gcc; CXX=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-oxide-g++; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin; TRIPLE=x86_64-buildroot-linux-musl; TCSYS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/x86_64-buildroot-linux-musl/sysroot; fi
UAPI=""
export TCSYS PATH="$TCBIN:$PATH:$SYS/usr/bin"
export CC_FOR_BUILD=gcc BUILD_CC=gcc CXX
unset CFLAGS CXXFLAGS CPPFLAGS LDFLAGS
[ -f Makefile ] && make distclean >/dev/null 2>&1 || true
export CC CROSS UAPI
export CFLAGS="-Os -fPIC  -I$SYS/usr/include -Wno-poison-system-directories $UAPI"
export LDFLAGS="-Wl,-rpath-link,$SYS/usr/lib -L$SYS/usr/lib "
unset PKG_CONFIG_PATH
export PKG_CONFIG_LIBDIR="$SYS/usr/lib/pkgconfig" PKG_CONFIG_SYSROOT_DIR="$SYS"
if [ "%{_target_cpu}" = "aarch64" ]; then CMP=aarch64; else CMP=x86_64; fi
cat > oxide-tc.cmake <<EOF
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR $CMP)
set(CMAKE_C_COMPILER $CC)
set(CMAKE_CXX_COMPILER $CXX)
set(CMAKE_FIND_ROOT_PATH "$SYS;$TCSYS")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
EOF
cmake -S . -B _b -DCMAKE_TOOLCHAIN_FILE=$PWD/oxide-tc.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_USE_OPENSSL=OFF -DBUILD_TESTING=OFF -DBUILD_CursesDialog=OFF
cmake --build _b -j$(nproc)

%install
SYS=/home/nd/oxide/rpmbuild/sysroot/%{name}/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-oxide-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin; TCSYS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/aarch64-buildroot-linux-musl/sysroot; else CC=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-oxide-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin; TCSYS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/x86_64-buildroot-linux-musl/sysroot; fi
export CC CROSS TCSYS PATH="$TCBIN:$PATH:$SYS/usr/bin"
unset CFLAGS CXXFLAGS CPPFLAGS LDFLAGS
DESTDIR=%{buildroot} cmake --install _b
rm -f %{buildroot}%{_infodir}/dir
find %{buildroot} -name '*.la' -delete 2>/dev/null || true
( cd %{buildroot} && find . -type f -o -type l ) | sed 's#^\.\(.*\)#"\1"#' | LC_ALL=C sort > %{_builddir}/cmake.files

%files -f %{_builddir}/cmake.files
%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 3.31.6-1
- Generated oxide spec (script family).
