# Generated by vendorctl. build-system: go. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           duf
Version:        0.8.1
Release:        1%{?dist}
Summary:        duf: disk usage/free (oxide)
License:        MIT
Source0:        duf-0.8.1.tar.gz

%description
duf: disk usage/free (oxide)

%prep
%setup -q -n duf-0.8.1

%build
export PATH=/home/nd/oxide/oxide2/vendor/go/bin:$PATH
if [ "%{_target_cpu}" = "aarch64" ]; then GOARCH=arm64; else GOARCH=amd64; fi
CGO_ENABLED=0 GOOS=linux GOARCH=$GOARCH go build -ldflags='-s -w' -o %{name} .

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/bin
install -m0755 duf %{buildroot}/usr/bin/duf
( cd %{buildroot} && find . -type f -o -type l ) | sed 's#^\.##' | LC_ALL=C sort > %{_builddir}/duf.files

%files -f %{_builddir}/duf.files
%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 0.8.1-1
- Generated oxide spec (go family).
