# Generated by vendorctl. build-system: autotools. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           expat
Version:        2.6.2
Release:        1%{?dist}
Summary:        expat XML parser -devel (oxide)
License:        MIT
Source0:        expat-2.6.2.tar.xz

%description
expat XML parser -devel (oxide)

%prep
%setup -q -n expat-2.6.2

%build
. /home/nd/oxide/rpmbuild/lib/uapi-stage.sh
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc; UAPI="$(uapi_cflags aarch64)"; else CC=musl-gcc; UAPI="$(uapi_cflags x86_64)"; fi
[ -f Makefile ] && make distclean >/dev/null 2>&1 || true
find . \( -name '*.o' -o -name '*.a' -o -name '*.lo' -o -name '*.la' \) -delete 2>/dev/null || true
CC="$CC" CC_FOR_BUILD=gcc LDFLAGS_FOR_BUILD="" \
CFLAGS_FOR_BUILD="-D_GNU_SOURCE -Wno-implicit-function-declaration -Wno-incompatible-pointer-types" \
CFLAGS="-Os -D_GNU_SOURCE -fPIC -Wno-implicit-function-declaration -Wno-incompatible-pointer-types $UAPI" \
LDFLAGS="-static" \
./configure --host=%{_target_cpu}-linux-musl --prefix=/usr --enable-shared --disable-static --without-docbook --without-examples --without-tests
make %{?_smp_mflags}

%install
make install DESTDIR=%{buildroot} INSTALL='install -p'
rm -f %{buildroot}%{_infodir}/dir
find %{buildroot} -name '*.la' -delete 2>/dev/null || true
( cd %{buildroot} && find . -type f -o -type l ) | sed 's#^\.##' | LC_ALL=C sort > %{_builddir}/expat.files

%files -f %{_builddir}/expat.files
%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 2.6.2-1
- Generated oxide spec (autotools family).
