# Generated by vendorctl. build-system: cargo. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           eza
Version:        0.20.24
Release:        1%{?dist}
Summary:        eza: modern ls (oxide)
License:        MIT
Source0:        %{name}-%{version}.tar.gz

%description
eza: modern ls (oxide)

%prep
%setup -q -n eza-0.20.24

%build
unset CC CXX CPP CFLAGS CXXFLAGS CPPFLAGS LDFLAGS
if [ "%{_target_cpu}" = "aarch64" ]; then TGT=aarch64-unknown-linux-musl; export PATH="/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin:$PATH"; export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc; export CC_aarch64_unknown_linux_musl=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc; else TGT=x86_64-unknown-linux-musl; fi
rustup target add $TGT >/dev/null 2>&1 || true
RUSTFLAGS="-C target-feature=+crt-static" cargo build --release --target $TGT 

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/bin
install -m0755 target/%{_target_cpu}-unknown-linux-musl/release/eza %{buildroot}/usr/bin/eza
B=target/%{_target_cpu}-unknown-linux-musl/release/build
find $B -path '*/out/*' -name '*.1' 2>/dev/null | while read f; do install -Dm644 "$f" %{buildroot}%{_mandir}/man1/"$(basename "$f")"; done
find $B -path '*/out/*' \( -name '*.bash' -o -name '*.bash-completion' \) 2>/dev/null | while read f; do n=$(basename "$f"); n=${n%.bash}; n=${n%.bash-completion}; install -Dm644 "$f" %{buildroot}%{_datadir}/bash-completion/completions/"$n"; done
find $B -path '*/out/*' -name '_*' 2>/dev/null | while read f; do install -Dm644 "$f" %{buildroot}%{_datadir}/zsh/site-functions/"$(basename "$f")"; done
find $B -path '*/out/*' -name '*.fish' 2>/dev/null | while read f; do install -Dm644 "$f" %{buildroot}%{_datadir}/fish/vendor_completions.d/"$(basename "$f")"; done
( cd %{buildroot} && find . -type f -o -type l ) | sed 's#^\.##' | LC_ALL=C sort > %{_builddir}/eza.files

%files -f %{_builddir}/eza.files
%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 0.20.24-1
- Generated oxide spec (cargo family).
