# Generated by vendorctl. build-system: autotools. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           findutils
Version:        4.10.0
Release:        1%{?dist}
Summary:        GNU findutils (static-musl, oxide)
License:        GPL-3.0-or-later
Source0:        %{name}-%{version}.tar.gz

%description
GNU findutils (static-musl, oxide)

%prep
%setup -q

%build
. /home/nd/oxide/rpmbuild/lib/uapi-stage.sh
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc; UAPI="$(uapi_cflags aarch64)"; else CC=musl-gcc; UAPI="$(uapi_cflags x86_64)"; fi
[ -f Makefile ] && make distclean >/dev/null 2>&1 || true
find . \( -name '*.o' -o -name '*.a' -o -name '*.lo' -o -name '*.la' \) -delete 2>/dev/null || true
CC="$CC" CC_FOR_BUILD=gcc LDFLAGS_FOR_BUILD="" \
CFLAGS_FOR_BUILD="-D_GNU_SOURCE -Wno-implicit-function-declaration -Wno-incompatible-pointer-types" \
CFLAGS="-Os -D_GNU_SOURCE  -Wno-implicit-function-declaration -Wno-incompatible-pointer-types $UAPI" \
LDFLAGS="-static" \
./configure --host=%{_target_cpu}-linux-musl --disable-nls --without-selinux --prefix=/usr
make %{?_smp_mflags}

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/bin
install -m0755 find/find %{buildroot}/usr/bin/find
mkdir -p %{buildroot}/usr/bin
install -m0755 xargs/xargs %{buildroot}/usr/bin/xargs

%files
/usr/bin/find
/usr/bin/xargs

%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 4.10.0-1
- Generated oxide spec (autotools family).
