# Generated by vendorctl. build-system: go. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           fzf
Version:        0.55.0
Release:        1%{?dist}
Summary:        fzf: fuzzy finder (oxide)
License:        MIT
Source0:        fzf-0.55.0.tar.gz

%description
fzf: fuzzy finder (oxide)

%prep
%setup -q -n fzf-0.55.0

%build
export PATH=/home/nd/oxide/oxide2/vendor/go/bin:$PATH
if [ "%{_target_cpu}" = "aarch64" ]; then GOARCH=arm64; else GOARCH=amd64; fi
CGO_ENABLED=0 GOOS=linux GOARCH=$GOARCH go build -ldflags='-s -w' -o %{name} .

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/bin
install -m0755 fzf %{buildroot}/usr/bin/fzf
( cd %{buildroot} && find . -type f -o -type l ) | sed 's#^\.##' | LC_ALL=C sort > %{_builddir}/fzf.files

%files -f %{_builddir}/fzf.files
%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 0.55.0-1
- Generated oxide spec (go family).
