# Generated by vendorctl. build-system: script. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           go
Version:        1.23.4
Release:        1%{?dist}
Summary:        Go toolchain (oxide native)
License:        BSD-3-Clause
Source0:        go-1.23.4.tar.gz

%description
Go toolchain (oxide native)

%prep
%setup -q -n go

%build
SYS=/home/nd/oxide/rpmbuild/sysroot/%{name}/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-oxide-gcc; CXX=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-oxide-g++; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin; TRIPLE=aarch64-buildroot-linux-musl; TCSYS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/aarch64-buildroot-linux-musl/sysroot; else CC=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-oxide-gcc; CXX=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-oxide-g++; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin; TRIPLE=x86_64-buildroot-linux-musl; TCSYS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/x86_64-buildroot-linux-musl/sysroot; fi
UAPI=""
export TCSYS PATH="$TCBIN:$PATH:$SYS/usr/bin"
export CC_FOR_BUILD=gcc BUILD_CC=gcc CXX
unset CFLAGS CXXFLAGS CPPFLAGS LDFLAGS
[ -f Makefile ] && make distclean >/dev/null 2>&1 || true
find . \( -name '*.o' -o -name '*.a' -o -name '*.lo' -o -name '*.la' \) -delete 2>/dev/null || true
export CC CROSS UAPI
export CFLAGS="-Os -fPIC  -I$SYS/usr/include -Wno-poison-system-directories $UAPI"
export LDFLAGS="-Wl,-rpath-link,$SYS/usr/lib -L$SYS/usr/lib "
unset PKG_CONFIG_PATH
export PKG_CONFIG_LIBDIR="$SYS/usr/lib/pkgconfig" PKG_CONFIG_SYSROOT_DIR="$SYS"
if [ "%{_target_cpu}" = "aarch64" ]; then GA=arm64; else GA=amd64; fi
cd src && GOROOT_BOOTSTRAP=/home/nd/oxide/oxide2/vendor/go CGO_ENABLED=0 GOROOT_FINAL=/usr/lib/go ./make.bash && cd .. && GOOS=linux GOARCH=$GA CGO_ENABLED=0 ./bin/go install -a std cmd

%install
SYS=/home/nd/oxide/rpmbuild/sysroot/%{name}/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-oxide-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin; TCSYS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/aarch64-buildroot-linux-musl/sysroot; else CC=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-oxide-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin; TCSYS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/x86_64-buildroot-linux-musl/sysroot; fi
export CC CROSS TCSYS PATH="$TCBIN:$PATH:$SYS/usr/bin"
unset CFLAGS CXXFLAGS CPPFLAGS LDFLAGS
if [ "%{_target_cpu}" = "aarch64" ]; then GA=arm64; else GA=amd64; fi
mkdir -p %{buildroot}/usr/lib/go %{buildroot}/usr/bin
cp -a bin pkg src lib api go.env VERSION %{buildroot}/usr/lib/go/ 2>/dev/null
if [ -d %{buildroot}/usr/lib/go/bin/linux_$GA ]; then rm -f %{buildroot}/usr/lib/go/bin/go %{buildroot}/usr/lib/go/bin/gofmt; mv %{buildroot}/usr/lib/go/bin/linux_$GA/* %{buildroot}/usr/lib/go/bin/; rmdir %{buildroot}/usr/lib/go/bin/linux_$GA; fi
ln -sf ../lib/go/bin/go %{buildroot}/usr/bin/go; ln -sf ../lib/go/bin/gofmt %{buildroot}/usr/bin/gofmt
rm -f %{buildroot}%{_infodir}/dir
find %{buildroot} -name '*.la' -delete 2>/dev/null || true
( cd %{buildroot} && find . -type f -o -type l ) | sed 's#^\.##' | LC_ALL=C sort > %{_builddir}/go.files

%files -f %{_builddir}/go.files
%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 1.23.4-1
- Generated oxide spec (script family).
