# Generated by vendorctl. build-system: cargo. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           hyperfine
Version:        1.19.0
Release:        1%{?dist}
Summary:        hyperfine: benchmarking tool (oxide)
License:        MIT OR Apache-2.0
Source0:        hyperfine-1.19.0.tar.gz

%description
hyperfine: benchmarking tool (oxide)

%prep
%setup -q -n hyperfine-1.19.0

%build
unset CC CXX CPP CFLAGS CXXFLAGS CPPFLAGS LDFLAGS
if [ "%{_target_cpu}" = "aarch64" ]; then TGT=aarch64-unknown-linux-musl; G=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc; else TGT=x86_64-unknown-linux-musl; G=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc; fi
export PATH="$(dirname $G):$PATH"
V=$(echo $TGT | tr 'a-z-' 'A-Z_'); export CARGO_TARGET_${V}_LINKER=$G
export CC_$(echo $TGT | tr - _)=$G
rustup target add $TGT >/dev/null 2>&1 || true
RUSTFLAGS="-C target-feature=+crt-static" cargo build --release --target $TGT 

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/bin
install -m0755 target/%{_target_cpu}-unknown-linux-musl/release/hyperfine %{buildroot}/usr/bin/hyperfine
B=target/%{_target_cpu}-unknown-linux-musl/release/build
find $B -path '*/out/*' -name '*.1' 2>/dev/null | while read f; do install -Dm644 "$f" %{buildroot}%{_mandir}/man1/"$(basename "$f")"; done
find $B -path '*/out/*' \( -name '*.bash' -o -name '*.bash-completion' \) 2>/dev/null | while read f; do n=$(basename "$f"); n=${n%.bash}; n=${n%.bash-completion}; install -Dm644 "$f" %{buildroot}%{_datadir}/bash-completion/completions/"$n"; done
find $B -path '*/out/*' -name '_*' 2>/dev/null | while read f; do install -Dm644 "$f" %{buildroot}%{_datadir}/zsh/site-functions/"$(basename "$f")"; done
find $B -path '*/out/*' -name '*.fish' 2>/dev/null | while read f; do install -Dm644 "$f" %{buildroot}%{_datadir}/fish/vendor_completions.d/"$(basename "$f")"; done
( cd %{buildroot} && find . -type f -o -type l ) | sed 's#^\.##' | LC_ALL=C sort > %{_builddir}/hyperfine.files

%files -f %{_builddir}/hyperfine.files
%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 1.19.0-1
- Generated oxide spec (cargo family).
