# Generated by vendorctl. build-system: script. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           libcap
Version:        2.69
Release:        1%{?dist}
Summary:        libcap (oxide)
License:        BSD-3-Clause OR GPL-2.0-only
Source0:        libcap-2.69.tar.xz

%description
libcap (oxide)

%prep
%setup -q -n libcap-2.69

%build
SYS=/home/nd/oxide/rpmbuild/sysroot/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin; else CC=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin/x86_64-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin; fi
UAPI=""
export PATH="$TCBIN:$PATH"
export CC_FOR_BUILD=gcc BUILD_CC=gcc CXX="${CROSS}g++"
export CC CROSS UAPI
export CFLAGS="-Os -fPIC  -I$SYS/usr/include $UAPI"
export LDFLAGS="-Wl,-rpath,/usr/lib -L$SYS/usr/lib "
export PKG_CONFIG_PATH="$SYS/usr/lib/pkgconfig"
make -C libcap CC="$CC" BUILD_CC=gcc AR="${CROSS}ar" RANLIB="${CROSS}ranlib" OBJCOPY="${CROSS}objcopy" SHARED=yes %{?_smp_mflags}

%install
if [ "%{_target_cpu}" = "aarch64" ]; then export PATH=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin:$PATH; else export PATH=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin:$PATH; fi
make -C libcap install DESTDIR=%{buildroot} prefix=/usr lib=lib SHARED=yes RAISE_SETFCAP=no
rm -f %{buildroot}%{_infodir}/dir
find %{buildroot} -name '*.la' -delete 2>/dev/null || true
( cd %{buildroot} && find . -type f -o -type l ) | sed 's#^\.##' | LC_ALL=C sort > %{_builddir}/libcap.files

%files -f %{_builddir}/libcap.files
%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 2.69-1
- Generated oxide spec (script family).
