# Generated by vendorctl. build-system: go. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           micro
Version:        2.0.14
Release:        1%{?dist}
Summary:        micro: terminal editor (oxide)
License:        MIT
Source0:        micro-2.0.14.tar.gz

%description
micro: terminal editor (oxide)

%prep
%setup -q -n micro-2.0.14

%build
export PATH=/home/nd/oxide/oxide2/vendor/go/bin:$PATH
if [ "%{_target_cpu}" = "aarch64" ]; then GOARCH=arm64; else GOARCH=amd64; fi
CGO_ENABLED=0 GOOS=linux GOARCH=$GOARCH go build -ldflags='-s -w' -o %{name} ./cmd/micro

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/bin
install -m0755 micro %{buildroot}/usr/bin/micro
( cd %{buildroot} && find . -type f -o -type l ) | sed 's#^\.##' | LC_ALL=C sort > %{_builddir}/micro.files

%files -f %{_builddir}/micro.files
%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 2.0.14-1
- Generated oxide spec (go family).
