# Generated by vendorctl. build-system: stage. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           musl-dev
Version:        1.2.5
Release:        1%{?dist}
Summary:        musl libc headers + static libs + crt (oxide dev)
License:        MIT

%description
musl libc headers + static libs + crt (oxide dev)

%prep


%build

%install
SYS=/home/nd/oxide/rpmbuild/sysroot/%{name}/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-oxide-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin; TCSYS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/aarch64-buildroot-linux-musl/sysroot; else CC=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-oxide-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin; TCSYS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/x86_64-buildroot-linux-musl/sysroot; fi
export CC CROSS TCSYS PATH="$SYS/usr/bin:$TCBIN:$PATH"
unset CFLAGS CXXFLAGS CPPFLAGS LDFLAGS
mkdir -p %{buildroot}/usr/include %{buildroot}/usr/lib; cp -a $TCSYS/usr/include/. %{buildroot}/usr/include/; for f in crt1.o crti.o crtn.o Scrt1.o rcrt1.o libc.a libc.so libm.a libpthread.a libdl.a librt.a libcrypt.a libresolv.a libutil.a libxnet.a; do cp -a $TCSYS/lib/$f %{buildroot}/usr/lib/ 2>/dev/null || true; done
( cd %{buildroot} && find . -type f -o -type l ) | sed 's#^\.##' | LC_ALL=C sort > %{_builddir}/musl-dev.files

%files -f %{_builddir}/musl-dev.files
%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 1.2.5-1
- Generated oxide spec (stage family).
