# Generated by vendorctl. build-system: script. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           openssl
Version:        3.0.15
Release:        1%{?dist}
Summary:        OpenSSL -devel (oxide)
License:        Apache-2.0
Source0:        openssl-3.0.15.tar.gz

%description
OpenSSL -devel (oxide)

%prep
%setup -q -n openssl-3.0.15

%build
SYS=/home/nd/oxide/rpmbuild/sysroot/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin; else CC=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin/x86_64-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin; fi
UAPI=""
export PATH="$TCBIN:$PATH"
export CC_FOR_BUILD=gcc BUILD_CC=gcc CXX="${CROSS}g++"
export CC CROSS UAPI
export CFLAGS="-Os -fPIC  -I$SYS/usr/include $UAPI"
export LDFLAGS="-Wl,-rpath,/usr/lib -L$SYS/usr/lib "
export PKG_CONFIG_PATH="$SYS/usr/lib/pkgconfig"
unset CC; ./Configure linux-%{_target_cpu} --cross-compile-prefix=$CROSS shared no-tests no-module no-legacy --prefix=/usr --libdir=lib && make %{?_smp_mflags}

%install
if [ "%{_target_cpu}" = "aarch64" ]; then export PATH=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin:$PATH; else export PATH=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin:$PATH; fi
make install_sw DESTDIR=%{buildroot}
rm -f %{buildroot}%{_infodir}/dir
find %{buildroot} -name '*.la' -delete 2>/dev/null || true
( cd %{buildroot} && find . -type f -o -type l ) | sed 's#^\.##' | LC_ALL=C sort > %{_builddir}/openssl.files

%files -f %{_builddir}/openssl.files
%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 3.0.15-1
- Generated oxide spec (script family).
