# Generated by vendorctl. build-system: meson. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           pam
Version:        1.7.2
Release:        1%{?dist}
Summary:        Linux-PAM (oxide)
License:        BSD-3-Clause
Source0:        Linux-PAM-1.7.2.tar.xz

%description
Linux-PAM (oxide)

%prep
%setup -q -n Linux-PAM-1.7.2

%build
SYS=/home/nd/oxide/rpmbuild/sysroot/%{name}/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-oxide-gcc; CXX=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-oxide-g++; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin; TRIPLE=aarch64-buildroot-linux-musl; else CC=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-oxide-gcc; CXX=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-oxide-g++; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin; TRIPLE=x86_64-buildroot-linux-musl; fi
UAPI=""
export PATH="$SYS/usr/bin:$TCBIN:$PATH"
export CC_FOR_BUILD=gcc BUILD_CC=gcc CXX
unset PKG_CONFIG_PATH
export PKG_CONFIG_LIBDIR="$SYS/usr/lib/pkgconfig" PKG_CONFIG_SYSROOT_DIR="$SYS"
cat > oxide-cross.ini <<OXEOF
[binaries]
c = '$CC'
ar = '${CROSS}ar'
strip = '${CROSS}strip'
pkg-config = 'pkg-config'
[host_machine]
system = 'linux'
cpu_family = '%{_target_cpu}'
cpu = '%{_target_cpu}'
endian = 'little'
[built-in options]
c_args = ['-I$SYS/usr/include', '-Wno-poison-system-directories']
c_link_args = ['-L$SYS/usr/lib', '-Wl,-rpath-link,$SYS/usr/lib']
[properties]
sys_root = '$SYS'
pkg_config_libdir = ['$SYS/usr/lib/pkgconfig']
OXEOF
rm -rf _b
meson setup _b --cross-file oxide-cross.ini --prefix=/usr --libdir=lib -Db_pie=false -Db_lundef=false -Db_staticpic=true -Ddocs=disabled -Daudit=disabled -Dselinux=disabled -Dnis=disabled -Di18n=disabled -Dlogind=disabled -Delogind=disabled -Deconf=disabled -Dpwaccess=disabled -Dopenssl=disabled -Dpam_userdb=disabled -Dexamples=false -Dxtests=false
ninja -C _b

%install
SYS=/home/nd/oxide/rpmbuild/sysroot/%{name}/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-oxide-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin; else CC=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-oxide-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin; fi
export CC CROSS PATH="$SYS/usr/bin:$TCBIN:$PATH"
unset CFLAGS CXXFLAGS CPPFLAGS LDFLAGS
DESTDIR=%{buildroot} ninja -C _b install
rm -f %{buildroot}%{_infodir}/dir
find %{buildroot} -name '*.la' -delete 2>/dev/null || true
( cd %{buildroot} && find . -type f -o -type l ) | sed 's#^\.##' | LC_ALL=C sort > %{_builddir}/pam.files

%files -f %{_builddir}/pam.files
%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 1.7.2-1
- Generated oxide spec (meson family).
