# Generated by vendorctl. build-system: autotools. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           patch
Version:        2.7.6
Release:        1%{?dist}
Summary:        GNU patch (static-musl, oxide)
License:        GPL-3.0-or-later
Source0:        %{name}-%{version}.tar.gz

%description
GNU patch (static-musl, oxide)

%prep
%setup -q

%build
. /home/nd/oxide/rpmbuild/lib/uapi-stage.sh
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc; UAPI="$(uapi_cflags aarch64)"; else CC=musl-gcc; UAPI="$(uapi_cflags x86_64)"; fi
CC="$CC" CC_FOR_BUILD=gcc LDFLAGS_FOR_BUILD="" \
CFLAGS_FOR_BUILD="-D_GNU_SOURCE -Wno-implicit-function-declaration -Wno-incompatible-pointer-types" \
CFLAGS="-Os -D_GNU_SOURCE -Wno-implicit-function-declaration -Wno-incompatible-pointer-types $UAPI" \
LDFLAGS="-static" \
./configure --host=%{_target_cpu}-linux-musl --disable-nls --prefix=/usr
make %{?_smp_mflags}

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/bin
install -m0755 src/patch %{buildroot}/usr/bin/patch

%files
/usr/bin/patch

%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 2.7.6-1
- Generated oxide spec (autotools family).
