# Generated by vendorctl. build-system: script. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           python
Version:        3.13.1
Release:        1%{?dist}
Summary:        Python 3.13 (oxide)
License:        PSF-2.0
Source0:        python-3.13.1.tar.gz

%description
Python 3.13 (oxide)

%prep
%setup -q -n Python-3.13.1

%build
SYS=/home/nd/oxide/rpmbuild/sysroot/%{name}/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-oxide-gcc; CXX=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-oxide-g++; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin; TRIPLE=aarch64-buildroot-linux-musl; TCSYS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/aarch64-buildroot-linux-musl/sysroot; else CC=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-oxide-gcc; CXX=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-oxide-g++; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin; TRIPLE=x86_64-buildroot-linux-musl; TCSYS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/x86_64-buildroot-linux-musl/sysroot; fi
UAPI=""
export TCSYS PATH="$TCBIN:$PATH:$SYS/usr/bin"
export CC_FOR_BUILD=gcc BUILD_CC=gcc CXX
unset CFLAGS CXXFLAGS CPPFLAGS LDFLAGS
[ -f Makefile ] && make distclean >/dev/null 2>&1 || true
export CC CROSS UAPI
export CFLAGS="-Os -fPIC  -I$SYS/usr/include -Wno-poison-system-directories $UAPI"
export LDFLAGS="-Wl,-rpath-link,$SYS/usr/lib -L$SYS/usr/lib "
unset PKG_CONFIG_PATH
export PKG_CONFIG_LIBDIR="$SYS/usr/lib/pkgconfig" PKG_CONFIG_SYSROOT_DIR="$SYS"
mkdir -p build-host && ( cd build-host && CC=gcc CXX=g++ ../configure -q >/dev/null && make -s -j$(nproc) python )
HOSTPY=$(pwd)/build-host/python
./configure --build=x86_64-pc-linux-gnu --host=$TRIPLE --with-build-python=$HOSTPY --prefix=/usr --disable-shared --without-ensurepip --with-openssl=$SYS/usr ac_cv_file__dev_ptmx=no ac_cv_file__dev_ptc=no ac_cv_buggy_getaddrinfo=no
make %{?_smp_mflags}

%install
SYS=/home/nd/oxide/rpmbuild/sysroot/%{name}/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-oxide-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin; TCSYS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/aarch64-buildroot-linux-musl/sysroot; else CC=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-oxide-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin; TCSYS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/x86_64-buildroot-linux-musl/sysroot; fi
export CC CROSS TCSYS PATH="$TCBIN:$PATH:$SYS/usr/bin"
unset CFLAGS CXXFLAGS CPPFLAGS LDFLAGS
make install DESTDIR=%{buildroot}
rm -f %{buildroot}%{_infodir}/dir
find %{buildroot} -name '*.la' -delete 2>/dev/null || true
( cd %{buildroot} && find . -type f -o -type l ) | sed 's#^\.##' | LC_ALL=C sort > %{_builddir}/python.files

%files -f %{_builddir}/python.files
%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 3.13.1-1
- Generated oxide spec (script family).
