# Generated by vendorctl. build-system: cargo. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           ripgrep
Version:        14.1.1
Release:        1%{?dist}
Summary:        ripgrep: recursive grep (oxide)
License:        MIT OR Unlicense
Source0:        %{name}-%{version}.tar.gz

%description
ripgrep: recursive grep (oxide)

%prep
%setup -q -n ripgrep-14.1.1

%build
unset CC CXX CPP CFLAGS CXXFLAGS CPPFLAGS LDFLAGS
if [ "%{_target_cpu}" = "aarch64" ]; then TGT=aarch64-unknown-linux-musl; export PATH="/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin:$PATH"; export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc; export CC_aarch64_unknown_linux_musl=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc; else TGT=x86_64-unknown-linux-musl; fi
rustup target add $TGT >/dev/null 2>&1 || true
RUSTFLAGS="-C target-feature=+crt-static" cargo build --release --target $TGT 

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/bin
install -m0755 target/%{_target_cpu}-unknown-linux-musl/release/rg %{buildroot}/usr/bin/rg

%files
/usr/bin/rg

%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 14.1.1-1
- Generated oxide spec (cargo family).
