# Generated by vendorctl. build-system: script. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           rust
Version:        1.84.0
Release:        1%{?dist}
Summary:        Rust toolchain — rustc/cargo (oxide native)
License:        MIT OR Apache-2.0
Source0:        rust-1.84.0.tar.gz

%description
Rust toolchain — rustc/cargo (oxide native)

%prep
%setup -q -n rustc-1.84.0-src


%build
SYS=/home/nd/oxide/rpmbuild/sysroot/%{name}/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-oxide-gcc; CXX=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-oxide-g++; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin; TRIPLE=aarch64-buildroot-linux-musl; TCSYS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/aarch64-buildroot-linux-musl/sysroot; else CC=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-oxide-gcc; CXX=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-oxide-g++; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin; TRIPLE=x86_64-buildroot-linux-musl; TCSYS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/x86_64-buildroot-linux-musl/sysroot; fi
UAPI=""
export TCSYS PATH="$TCBIN:$PATH:$SYS/usr/bin"
export CC_FOR_BUILD=gcc BUILD_CC=gcc CXX
unset CFLAGS CXXFLAGS CPPFLAGS LDFLAGS
[ -f Makefile ] && make distclean >/dev/null 2>&1 || true
export CC CROSS UAPI
export CFLAGS="-Os -fPIC -D_GNU_SOURCE  -I$SYS/usr/include -Wno-poison-system-directories $UAPI"
export LDFLAGS="-Wl,-rpath-link,$SYS/usr/lib -L$SYS/usr/lib "
unset PKG_CONFIG_PATH
export PKG_CONFIG_LIBDIR="$SYS/usr/lib/pkgconfig" PKG_CONFIG_SYSROOT_DIR="$SYS"
if [ "%{_target_cpu}" = "aarch64" ]; then RT=aarch64-unknown-linux-musl; else RT=x86_64-unknown-linux-musl; fi
cat > config.toml <<EOF
[llvm]
download-ci-llvm = false
[build]
build = "x86_64-unknown-linux-gnu"
host = ["$RT"]
target = ["$RT"]
docs = false
extended = true
tools = ["cargo"]
[install]
prefix = "/usr"
sysconfdir = "/etc"
[rust]
channel = "stable"
download-rustc = false
[target.$RT]
cc = "$CC"
cxx = "$CXX"
linker = "$CC"
ar = "${CROSS}ar"
ranlib = "${CROSS}ranlib"
musl-root = "$TCSYS"
crt-static = false
[target.x86_64-unknown-linux-gnu]
cc = "gcc"
cxx = "g++"
EOF
python3 x.py build --stage 2

%install
SYS=/home/nd/oxide/rpmbuild/sysroot/%{name}/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-oxide-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin; TCSYS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/aarch64-buildroot-linux-musl/sysroot; else CC=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-oxide-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin; TCSYS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/x86_64-buildroot-linux-musl/sysroot; fi
export CC CROSS TCSYS PATH="$TCBIN:$PATH:$SYS/usr/bin"
unset CFLAGS CXXFLAGS CPPFLAGS LDFLAGS
DESTDIR=%{buildroot} python3 x.py install
rm -f %{buildroot}%{_infodir}/dir
find %{buildroot} -name '*.la' -delete 2>/dev/null || true
( cd %{buildroot} && find . -type f -o -type l ) | sed 's#^\.\(.*\)#"\1"#' | LC_ALL=C sort > %{_builddir}/rust.files

%files -f %{_builddir}/rust.files
%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 1.84.0-1
- Generated oxide spec (script family).
