# Generated by vendorctl. build-system: autotools. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           sed
Version:        4.9
Release:        1%{?dist}
Summary:        GNU sed (static-musl, oxide)
License:        GPL-3.0-or-later
Source0:        sed-4.9.tar.xz

%description
GNU sed (static-musl, oxide)

%prep
%setup -q -n sed-4.9

%build
SYS=/home/nd/oxide/rpmbuild/sysroot/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-; else CC=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin/x86_64-linux-musl-; fi
UAPI=""
export AR="${CROSS}ar" RANLIB="${CROSS}ranlib" NM="${CROSS}nm" STRIP="${CROSS}strip"
export C_INCLUDE_PATH="$SYS/usr/include" CPLUS_INCLUDE_PATH="$SYS/usr/include" LIBRARY_PATH="$SYS/usr/lib"
[ -f Makefile ] && make distclean >/dev/null 2>&1 || true
find . \( -name '*.o' -o -name '*.a' -o -name '*.lo' -o -name '*.la' \) -delete 2>/dev/null || true
CC="$CC" CC_FOR_BUILD=gcc LDFLAGS_FOR_BUILD="" \
CFLAGS_FOR_BUILD="-D_GNU_SOURCE -Wno-implicit-function-declaration -Wno-incompatible-pointer-types -Wno-int-conversion" \
CFLAGS="-Os -D_GNU_SOURCE  -I$SYS/usr/include -Wno-implicit-function-declaration -Wno-incompatible-pointer-types -Wno-int-conversion $UAPI" \
LDFLAGS="-Wl,-rpath,/usr/lib -L$SYS/usr/lib " \
PKG_CONFIG_PATH="$SYS/usr/lib/pkgconfig" \
LD_LIBRARY_PATH="$SYS/usr/lib" \
./configure --build=x86_64-pc-linux-gnu --host=%{_target_cpu}-linux-musl --disable-nls --disable-acl --disable-i18n --without-selinux --prefix=/usr
make %{?_smp_mflags}

%install
make install DESTDIR=%{buildroot} INSTALL='install -p'
rm -f %{buildroot}%{_infodir}/dir
find %{buildroot} -name '*.la' -delete 2>/dev/null || true
( cd %{buildroot} && find . -type f -o -type l ) | sed 's#^\.##' | LC_ALL=C sort > %{_builddir}/sed.files

%files -f %{_builddir}/sed.files
%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 4.9-1
- Generated oxide spec (autotools family).
