# Generated by vendorctl. build-system: script. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           tree
Version:        2.2.1
Release:        1%{?dist}
Summary:        tree (oxide)
License:        GPL-2.0-or-later
Source0:        tree-2.2.1.tar.gz

%description
tree (oxide)

%prep
%setup -q -n unix-tree-2.2.1

%build
SYS=/home/nd/oxide/rpmbuild/sysroot/%{name}/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin; else CC=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin/x86_64-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin; fi
UAPI=""
export PATH="$SYS/usr/bin:$TCBIN:$PATH"
export CC_FOR_BUILD=gcc BUILD_CC=gcc CXX="${CROSS}g++"
export CC CROSS UAPI
export CFLAGS="-Os -fPIC  -I$SYS/usr/include $UAPI"
export LDFLAGS="-Wl,-rpath,/usr/lib -Wl,-rpath-link,$SYS/usr/lib -L$SYS/usr/lib "
export PKG_CONFIG_PATH="$SYS/usr/lib/pkgconfig"
make CC="$CC" %{?_smp_mflags}

%install
SYS=/home/nd/oxide/rpmbuild/sysroot/%{name}/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin; else CC=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin/x86_64-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin; fi
export CC CROSS PATH="$SYS/usr/bin:$TCBIN:$PATH"
unset CFLAGS CXXFLAGS CPPFLAGS LDFLAGS
make install PREFIX=%{buildroot}/usr MANDIR=%{buildroot}/usr/share/man
rm -f %{buildroot}%{_infodir}/dir
find %{buildroot} -name '*.la' -delete 2>/dev/null || true
( cd %{buildroot} && find . -type f -o -type l ) | sed 's#^\.##' | LC_ALL=C sort > %{_builddir}/tree.files

%files -f %{_builddir}/tree.files
%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 2.2.1-1
- Generated oxide spec (script family).
