# Generated by vendorctl. build-system: autotools. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           vim
Version:        9.1.0950
Release:        1%{?dist}
Summary:        vim (oxide)
License:        Vim
Source0:        vim-9.1.0950.tar.gz

%description
vim (oxide)

%prep
%setup -q -n vim-9.1.0950

%build
SYS=/home/nd/oxide/rpmbuild/sysroot/%{name}/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin; else CC=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin/x86_64-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin; fi
UAPI=""
export PATH="$SYS/usr/bin:$TCBIN:$PATH"
export CC_FOR_BUILD=gcc BUILD_CC=gcc CXX="${CROSS}g++"
[ -f Makefile ] && make distclean >/dev/null 2>&1 || true
find . \( -name '*.o' -o -name '*.a' -o -name '*.lo' -o -name '*.la' \) -delete 2>/dev/null || true
CC="$CC" CC_FOR_BUILD=gcc LDFLAGS_FOR_BUILD="" \
CFLAGS_FOR_BUILD="-D_GNU_SOURCE -Wno-implicit-function-declaration -Wno-incompatible-pointer-types -Wno-int-conversion" \
CFLAGS="-Os -D_GNU_SOURCE  -I$SYS/usr/include -Wno-implicit-function-declaration -Wno-incompatible-pointer-types -Wno-int-conversion $UAPI" \
LDFLAGS="-Wl,-rpath,/usr/lib -Wl,-rpath-link,$SYS/usr/lib -L$SYS/usr/lib " \
PKG_CONFIG_PATH="$SYS/usr/lib/pkgconfig" \
./configure --build=x86_64-pc-linux-gnu --host=%{_target_cpu}-linux-musl --prefix=/usr --with-tlib=ncursesw --with-features=tiny --disable-gui --disable-gtktest --without-x --disable-nls --disable-acl --disable-selinux --disable-channel --disable-netbeans --disable-perlinterp --disable-pythoninterp --disable-python3interp --disable-rubyinterp --disable-tclinterp --disable-luainterp
make %{?_smp_mflags}

%install
SYS=/home/nd/oxide/rpmbuild/sysroot/%{name}/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin; else CC=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin/x86_64-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin; fi
export CC CROSS PATH="$SYS/usr/bin:$TCBIN:$PATH"
unset CFLAGS CXXFLAGS CPPFLAGS LDFLAGS
make install DESTDIR=%{buildroot} INSTALL='install -p'
rm -f %{buildroot}%{_infodir}/dir
find %{buildroot} -name '*.la' -delete 2>/dev/null || true
( cd %{buildroot} && find . -type f -o -type l ) | sed 's#^\.##' | LC_ALL=C sort > %{_builddir}/vim.files

%files -f %{_builddir}/vim.files
%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 9.1.0950-1
- Generated oxide spec (autotools family).
