# Generated by vendorctl. build-system: script. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           vim
Version:        9.1.0950
Release:        1%{?dist}
Summary:        vim (oxide)
License:        Vim
Source0:        vim-9.1.0950.tar.gz

%description
vim (oxide)

%prep
%setup -q -n vim-9.1.0950

%build
SYS=/home/nd/oxide/rpmbuild/sysroot/%{name}/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-oxide-gcc; CXX=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-oxide-g++; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin; TRIPLE=aarch64-buildroot-linux-musl; else CC=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-oxide-gcc; CXX=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-oxide-g++; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin; TRIPLE=x86_64-buildroot-linux-musl; fi
UAPI=""
export PATH="$SYS/usr/bin:$TCBIN:$PATH"
export CC_FOR_BUILD=gcc BUILD_CC=gcc CXX
[ -f Makefile ] && make distclean >/dev/null 2>&1 || true
find . \( -name '*.o' -o -name '*.a' -o -name '*.lo' -o -name '*.la' \) -delete 2>/dev/null || true
export CC CROSS UAPI
export CFLAGS="-Os -fPIC  -I$SYS/usr/include -Wno-poison-system-directories $UAPI"
export LDFLAGS="-Wl,-rpath-link,$SYS/usr/lib -L$SYS/usr/lib "
unset PKG_CONFIG_PATH
export PKG_CONFIG_LIBDIR="$SYS/usr/lib/pkgconfig" PKG_CONFIG_SYSROOT_DIR="$SYS"
cd src && cat > auto/config.cache <<CACHE
ac_cv_header_termcap_h=no
vim_cv_getcwd_broken=no
vim_cv_memmove_handles_overlap=yes
vim_cv_stat_ignores_slash=no
vim_cv_tgetent=zero
vim_cv_terminfo=yes
vim_cv_toupper_broken=no
vim_cv_timer_create=yes
CACHE
./configure --cache-file=auto/config.cache --build=$(gcc -dumpmachine) --host=$TRIPLE --prefix=/usr --with-tlib=tinfow --with-features=huge --enable-multibyte --disable-gui --disable-gtktest --without-x --disable-nls --disable-selinux --disable-netbeans && make %{?_smp_mflags}

%install
SYS=/home/nd/oxide/rpmbuild/sysroot/%{name}/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-oxide-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin/aarch64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64--musl--stable-2025.08-1/bin; else CC=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-oxide-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin/x86_64-buildroot-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86-64--musl--stable-2025.08-1/bin; fi
export CC CROSS PATH="$SYS/usr/bin:$TCBIN:$PATH"
unset CFLAGS CXXFLAGS CPPFLAGS LDFLAGS
install -Dm755 src/vim %{buildroot}/usr/bin/vim; for l in vi view ex rvim rview; do ln -sf vim %{buildroot}/usr/bin/$l; done; mkdir -p %{buildroot}/usr/share/vim/vim91; cp -a runtime/. %{buildroot}/usr/share/vim/vim91/
rm -f %{buildroot}%{_infodir}/dir
find %{buildroot} -name '*.la' -delete 2>/dev/null || true
( cd %{buildroot} && find . -type f -o -type l ) | sed 's#^\.##' | LC_ALL=C sort > %{_builddir}/vim.files

%files -f %{_builddir}/vim.files
%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 9.1.0950-1
- Generated oxide spec (script family).
