# Generated by vendorctl. build-system: go. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           yq
Version:        4.44.3
Release:        1%{?dist}
Summary:        yq: YAML processor (oxide)
License:        MIT
Source0:        yq-4.44.3.tar.gz

%description
yq: YAML processor (oxide)

%prep
%setup -q -n yq-4.44.3

%build
export PATH=/home/nd/oxide/oxide2/vendor/go/bin:$PATH
if [ "%{_target_cpu}" = "aarch64" ]; then GOARCH=arm64; else GOARCH=amd64; fi
CGO_ENABLED=0 GOOS=linux GOARCH=$GOARCH go build -ldflags='-s -w' -o %{name} .

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/bin
install -m0755 yq %{buildroot}/usr/bin/yq
( cd %{buildroot} && find . -type f -o -type l ) | sed 's#^\.##' | LC_ALL=C sort > %{_builddir}/yq.files

%files -f %{_builddir}/yq.files
%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 4.44.3-1
- Generated oxide spec (go family).
