# Generated by vendorctl. build-system: script. Do not hand-edit; edit catalog + regen.
%global debug_package %{nil}
%global __global_compiler_flags %{nil}

Name:           zstd
Version:        1.5.6
Release:        1%{?dist}
Summary:        zstd (oxide)
License:        BSD-3-Clause
Source0:        zstd-1.5.6.tar.gz

%description
zstd (oxide)

%prep
%setup -q -n zstd-1.5.6

%build
SYS=/home/nd/oxide/rpmbuild/sysroot/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin; else CC=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin/x86_64-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin; fi
UAPI=""
export PATH="$SYS/usr/bin:$TCBIN:$PATH"
export CC_FOR_BUILD=gcc BUILD_CC=gcc CXX="${CROSS}g++"
export CC CROSS UAPI
export CFLAGS="-Os -fPIC  -I$SYS/usr/include $UAPI"
export LDFLAGS="-Wl,-rpath,/usr/lib -L$SYS/usr/lib "
export PKG_CONFIG_PATH="$SYS/usr/lib/pkgconfig"
make -C lib CC="$CC" CFLAGS="-O2 -fPIC" libzstd %{?_smp_mflags}

%install
SYS=/home/nd/oxide/rpmbuild/sysroot/%{_target_cpu}
if [ "%{_target_cpu}" = "aarch64" ]; then CC=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin/aarch64-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/aarch64-linux-musl-cross/bin; else CC=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc; CROSS=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin/x86_64-linux-musl-; TCBIN=/home/nd/oxide/oxide2/vendor/cross/x86_64-linux-musl-cross/bin; fi
export CC CROSS PATH="$SYS/usr/bin:$TCBIN:$PATH"
unset CFLAGS CXXFLAGS CPPFLAGS LDFLAGS
make -C lib install DESTDIR=%{buildroot} PREFIX=/usr
rm -f %{buildroot}%{_infodir}/dir
find %{buildroot} -name '*.la' -delete 2>/dev/null || true
( cd %{buildroot} && find . -type f -o -type l ) | sed 's#^\.##' | LC_ALL=C sort > %{_builddir}/zstd.files

%files -f %{_builddir}/zstd.files
%changelog
* Sat Jun 13 2026 Chris Watkins <chris@watkinslabs.com> - 1.5.6-1
- Generated oxide spec (script family).
